name: publish_nuget.yml
on:
    workflow_dispatch: # used to triger the job by hand
    push:
        tags: [ "v*" ]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Get  github tag versionß
                run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '8.0.x'

            -   name: Restore dependencies
                run: dotnet restore

            -   name: Build
                run: dotnet build --no-restore --configuration Release

            -   name: Pack
                run: dotnet pack --no-build --no-restore --configuration Release

            -   name: Publish *.nupkg to nuget.org
                run: dotnet nuget push **/bin/Release/Reditus.$RELEASE_VERSION.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
                env:
                    NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

            -   name: Publish *.snupkg to nuget.org
                run: dotnet nuget push **/bin/Release/Reditus.$RELEASE_VERSION.snupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
                env:
                    NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}